#pragma line 1 "VivadoTest/bla.cpp" ::: -10
#pragma line 1 "VivadoTest/bla.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 153 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "C:/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 407 "C:/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 189
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "VivadoTest/bla.cpp" 2 ::: 194
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\array" 1 3 ::: 195
#pragma line 32 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\array" 3 ::: 228
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\array" 3 ::: 229
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 1 3 ::: 230
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 1 3 ::: 291
#pragma line 63 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 344
#pragma line 90 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 362
#pragma line 187 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 389
#pragma line 197 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 391
#pragma line 207 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 393
#pragma line 217 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 395
#pragma line 238 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 397
#pragma line 258 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 403
#pragma line 272 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 406
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/os_defines.h" 1 3 ::: 411
#pragma line 57 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/os_defines.h" 3 ::: 456
#pragma line 276 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 2 3 ::: 461
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/cpu_defines.h" 1 3 ::: 465
#pragma line 279 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 2 3 ::: 494
#pragma line 339 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 530
#pragma line 379 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2/x86_64-w64-mingw32\\bits/c++config.h" 3 ::: 548
#pragma line 61 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 1351
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 1 3 ::: 1352
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 3 ::: 1394
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 1397
#pragma line 56 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 1433
#pragma line 44 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 2 3 ::: 1436
#pragma line 62 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 1447
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/functexcept.h" 1 3 ::: 1448
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\exception_defines.h" 1 3 ::: 1486
#pragma line 38 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/functexcept.h" 2 3 ::: 1525
#pragma line 63 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 1587
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/cpp_type_traits.h" 1 3 ::: 1588
#pragma line 36 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/cpp_type_traits.h" 3 ::: 1625
#pragma line 64 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 2035
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/type_traits.h" 1 3 ::: 2036
#pragma line 32 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/type_traits.h" 3 ::: 2069
#pragma line 65 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 2240
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/numeric_traits.h" 1 3 ::: 2241
#pragma line 32 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/numeric_traits.h" 3 ::: 2274
#pragma line 51 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/numeric_traits.h" 3 ::: 2283
#pragma line 96 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\ext/numeric_traits.h" 3 ::: 2308
#pragma line 66 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 2341
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_pair.h" 1 3 ::: 2342
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/move.h" 1 3 ::: 2403
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 1 3 ::: 2438
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 3 ::: 2480
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 2483
#pragma line 56 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 2508
#pragma line 44 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 2 3 ::: 2511
#pragma line 35 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/move.h" 2 3 ::: 2512
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/concept_check.h" 1 3 ::: 2513
#pragma line 33 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/concept_check.h" 3 ::: 2547
#pragma line 36 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/move.h" 2 3 ::: 2558
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\type_traits" 1 3 ::: 2561
#pragma line 32 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\type_traits" 3 ::: 2594
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\type_traits" 3 ::: 2595
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 1 3 ::: 2596
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 3 ::: 2638
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 2641
#pragma line 56 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 2666
#pragma line 44 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 2 3 ::: 2669
#pragma line 42 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\type_traits" 2 3 ::: 2670
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\tr1_impl/type_traits" 1 3 ::: 2679
#pragma line 63 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\tr1_impl/type_traits" 3 ::: 2727
#pragma line 51 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\type_traits" 2 3 ::: 3168
#pragma line 39 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/move.h" 2 3 ::: 3748
#pragma line 95 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/move.h" 3 ::: 3797
#pragma line 61 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_pair.h" 2 3 ::: 3830
#pragma line 67 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 4028
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator_base_types.h" 1 3 ::: 4029
#pragma line 63 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator_base_types.h" 3 ::: 4093
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 1 3 ::: 4096
#pragma line 41 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 3 ::: 4138
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 4141
#pragma line 56 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 4166
#pragma line 44 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\cstddef" 2 3 ::: 4169
#pragma line 66 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator_base_types.h" 2 3 ::: 4170
#pragma line 68 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 4284
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator_base_funcs.h" 1 3 ::: 4285
#pragma line 63 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator_base_funcs.h" 3 ::: 4349
#pragma line 69 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 4493
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator.h" 1 3 ::: 4494
#pragma line 68 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator.h" 3 ::: 4554
#pragma line 427 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator.h" 3 ::: 4906
#pragma line 517 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator.h" 3 ::: 4989
#pragma line 629 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_iterator.h" 3 ::: 5093
#pragma line 70 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 5535
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\debug/debug.h" 1 3 ::: 5537
#pragma line 72 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 2 3 ::: 5596
#pragma line 134 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\bits/stl_algobase.h" 3 ::: 5650
#pragma line 42 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\array" 2 3 ::: 6743
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\tr1_impl/array" 1 3 ::: 6752
#pragma line 51 "C:/Xilinx/Vivado_HLS/2015.4/win64/tools/clang/bin\\..\\lib\\clang\\3.1/../../../include/c++/4.5.2\\array" 2 3 ::: 7044
#pragma line 2 "VivadoTest/bla.cpp" 2 ::: 7045
#pragma line 1 "VivadoTest/bla.h" 1 ::: 7046
#pragma line 3 "VivadoTest/bla.cpp" 2 ::: 7050
